# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/joshua/Desktop/maya_python/righelper/src/righelper/resources/ui/ui_raw.ui',
# licensing of '/Users/joshua/Desktop/maya_python/righelper/src/righelper/resources/ui/ui_raw.ui' applies.
#
# Created: Mon Jun 21 14:09:31 2021
#      by: pyside2-uic  running on PySide2 5.12.5
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_RigHelper(object):
    def setupUi(self, RigHelper):
        RigHelper.setObjectName("RigHelper")
        RigHelper.resize(515, 600)
        RigHelper.setMinimumSize(QtCore.QSize(515, 400))
        self.centralwidget = QtWidgets.QWidget(RigHelper)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.posing_tab = QtWidgets.QWidget()
        self.posing_tab.setObjectName("posing_tab")
        self.gridLayout = QtWidgets.QGridLayout(self.posing_tab)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.keyAll = QtWidgets.QPushButton(self.posing_tab)
        self.keyAll.setMinimumSize(QtCore.QSize(150, 0))
        self.keyAll.setObjectName("keyAll")
        self.horizontalLayout_9.addWidget(self.keyAll)
        self.keyAll_translate = QtWidgets.QCheckBox(self.posing_tab)
        self.keyAll_translate.setChecked(True)
        self.keyAll_translate.setObjectName("keyAll_translate")
        self.horizontalLayout_9.addWidget(self.keyAll_translate)
        self.keyAll_rotate = QtWidgets.QCheckBox(self.posing_tab)
        self.keyAll_rotate.setObjectName("keyAll_rotate")
        self.horizontalLayout_9.addWidget(self.keyAll_rotate)
        self.keyAll_help = QtWidgets.QPushButton(self.posing_tab)
        self.keyAll_help.setMaximumSize(QtCore.QSize(24, 24))
        self.keyAll_help.setText("")
        self.keyAll_help.setObjectName("keyAll_help")
        self.horizontalLayout_9.addWidget(self.keyAll_help)
        self.gridLayout.addLayout(self.horizontalLayout_9, 8, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.selectGrp = QtWidgets.QPushButton(self.posing_tab)
        self.selectGrp.setMinimumSize(QtCore.QSize(150, 0))
        self.selectGrp.setObjectName("selectGrp")
        self.horizontalLayout_6.addWidget(self.selectGrp)
        self.selectGrp_out = QtWidgets.QLineEdit(self.posing_tab)
        self.selectGrp_out.setReadOnly(True)
        self.selectGrp_out.setObjectName("selectGrp_out")
        self.horizontalLayout_6.addWidget(self.selectGrp_out)
        self.selectGrp_help = QtWidgets.QPushButton(self.posing_tab)
        self.selectGrp_help.setMaximumSize(QtCore.QSize(24, 24))
        self.selectGrp_help.setText("")
        self.selectGrp_help.setObjectName("selectGrp_help")
        self.horizontalLayout_6.addWidget(self.selectGrp_help)
        self.gridLayout.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.centerGrp = QtWidgets.QPushButton(self.posing_tab)
        self.centerGrp.setEnabled(True)
        self.centerGrp.setMinimumSize(QtCore.QSize(150, 0))
        self.centerGrp.setObjectName("centerGrp")
        self.horizontalLayout_5.addWidget(self.centerGrp)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.centerGrp_help = QtWidgets.QPushButton(self.posing_tab)
        self.centerGrp_help.setMaximumSize(QtCore.QSize(24, 24))
        self.centerGrp_help.setText("")
        self.centerGrp_help.setObjectName("centerGrp_help")
        self.horizontalLayout_5.addWidget(self.centerGrp_help)
        self.gridLayout.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.zeroZ = QtWidgets.QPushButton(self.posing_tab)
        self.zeroZ.setMinimumSize(QtCore.QSize(150, 0))
        self.zeroZ.setObjectName("zeroZ")
        self.horizontalLayout.addWidget(self.zeroZ)
        self.zeroZ_sources = QtWidgets.QLineEdit(self.posing_tab)
        self.zeroZ_sources.setReadOnly(False)
        self.zeroZ_sources.setObjectName("zeroZ_sources")
        self.horizontalLayout.addWidget(self.zeroZ_sources)
        self.zeroZ_sel = QtWidgets.QPushButton(self.posing_tab)
        self.zeroZ_sel.setMaximumSize(QtCore.QSize(24, 24))
        self.zeroZ_sel.setText("")
        self.zeroZ_sel.setObjectName("zeroZ_sel")
        self.horizontalLayout.addWidget(self.zeroZ_sel)
        self.zeroZ_help = QtWidgets.QPushButton(self.posing_tab)
        self.zeroZ_help.setMaximumSize(QtCore.QSize(24, 24))
        self.zeroZ_help.setText("")
        self.zeroZ_help.setObjectName("zeroZ_help")
        self.horizontalLayout.addWidget(self.zeroZ_help)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.zeroLegs = QtWidgets.QPushButton(self.posing_tab)
        self.zeroLegs.setMinimumSize(QtCore.QSize(150, 0))
        self.zeroLegs.setObjectName("zeroLegs")
        self.horizontalLayout_2.addWidget(self.zeroLegs)
        self.zeroLegs_sources = QtWidgets.QLineEdit(self.posing_tab)
        self.zeroLegs_sources.setObjectName("zeroLegs_sources")
        self.horizontalLayout_2.addWidget(self.zeroLegs_sources)
        self.zeroLegs_sel = QtWidgets.QPushButton(self.posing_tab)
        self.zeroLegs_sel.setMaximumSize(QtCore.QSize(24, 24))
        self.zeroLegs_sel.setText("")
        self.zeroLegs_sel.setObjectName("zeroLegs_sel")
        self.horizontalLayout_2.addWidget(self.zeroLegs_sel)
        self.zeroLegs_help = QtWidgets.QPushButton(self.posing_tab)
        self.zeroLegs_help.setMaximumSize(QtCore.QSize(24, 24))
        self.zeroLegs_help.setText("")
        self.zeroLegs_help.setObjectName("zeroLegs_help")
        self.horizontalLayout_2.addWidget(self.zeroLegs_help)
        self.gridLayout.addLayout(self.horizontalLayout_2, 3, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.zeroSpines = QtWidgets.QPushButton(self.posing_tab)
        self.zeroSpines.setMinimumSize(QtCore.QSize(150, 0))
        self.zeroSpines.setObjectName("zeroSpines")
        self.horizontalLayout_3.addWidget(self.zeroSpines)
        self.zeroSpines_sources = QtWidgets.QLineEdit(self.posing_tab)
        self.zeroSpines_sources.setObjectName("zeroSpines_sources")
        self.horizontalLayout_3.addWidget(self.zeroSpines_sources)
        self.zeroSpines_sel = QtWidgets.QPushButton(self.posing_tab)
        self.zeroSpines_sel.setMaximumSize(QtCore.QSize(24, 24))
        self.zeroSpines_sel.setText("")
        self.zeroSpines_sel.setObjectName("zeroSpines_sel")
        self.horizontalLayout_3.addWidget(self.zeroSpines_sel)
        self.zeroSpines_help = QtWidgets.QPushButton(self.posing_tab)
        self.zeroSpines_help.setMaximumSize(QtCore.QSize(24, 24))
        self.zeroSpines_help.setText("")
        self.zeroSpines_help.setObjectName("zeroSpines_help")
        self.horizontalLayout_3.addWidget(self.zeroSpines_help)
        self.gridLayout.addLayout(self.horizontalLayout_3, 4, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.poseArms = QtWidgets.QPushButton(self.posing_tab)
        self.poseArms.setMinimumSize(QtCore.QSize(150, 0))
        self.poseArms.setObjectName("poseArms")
        self.horizontalLayout_4.addWidget(self.poseArms)
        self.poseArms_sources = QtWidgets.QLineEdit(self.posing_tab)
        self.poseArms_sources.setObjectName("poseArms_sources")
        self.horizontalLayout_4.addWidget(self.poseArms_sources)
        self.poseArms_sel = QtWidgets.QPushButton(self.posing_tab)
        self.poseArms_sel.setMaximumSize(QtCore.QSize(24, 24))
        self.poseArms_sel.setText("")
        self.poseArms_sel.setObjectName("poseArms_sel")
        self.horizontalLayout_4.addWidget(self.poseArms_sel)
        self.poseArms_help = QtWidgets.QPushButton(self.posing_tab)
        self.poseArms_help.setMaximumSize(QtCore.QSize(24, 24))
        self.poseArms_help.setText("")
        self.poseArms_help.setObjectName("poseArms_help")
        self.horizontalLayout_4.addWidget(self.poseArms_help)
        self.gridLayout.addLayout(self.horizontalLayout_4, 5, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.mirrorJoints = QtWidgets.QPushButton(self.posing_tab)
        self.mirrorJoints.setMinimumSize(QtCore.QSize(150, 0))
        self.mirrorJoints.setObjectName("mirrorJoints")
        self.horizontalLayout_7.addWidget(self.mirrorJoints)
        self.mirrorJoints_sources = QtWidgets.QLineEdit(self.posing_tab)
        self.mirrorJoints_sources.setObjectName("mirrorJoints_sources")
        self.horizontalLayout_7.addWidget(self.mirrorJoints_sources)
        self.mirrorJoints_sel = QtWidgets.QPushButton(self.posing_tab)
        self.mirrorJoints_sel.setMaximumSize(QtCore.QSize(24, 24))
        self.mirrorJoints_sel.setText("")
        self.mirrorJoints_sel.setObjectName("mirrorJoints_sel")
        self.horizontalLayout_7.addWidget(self.mirrorJoints_sel)
        self.mirrorJoints_help = QtWidgets.QPushButton(self.posing_tab)
        self.mirrorJoints_help.setMaximumSize(QtCore.QSize(24, 24))
        self.mirrorJoints_help.setText("")
        self.mirrorJoints_help.setObjectName("mirrorJoints_help")
        self.horizontalLayout_7.addWidget(self.mirrorJoints_help)
        self.gridLayout.addLayout(self.horizontalLayout_7, 6, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.restJoints = QtWidgets.QPushButton(self.posing_tab)
        self.restJoints.setMinimumSize(QtCore.QSize(150, 0))
        self.restJoints.setObjectName("restJoints")
        self.horizontalLayout_8.addWidget(self.restJoints)
        self.restJoints_sources = QtWidgets.QLineEdit(self.posing_tab)
        self.restJoints_sources.setObjectName("restJoints_sources")
        self.horizontalLayout_8.addWidget(self.restJoints_sources)
        self.restJoints_sel = QtWidgets.QPushButton(self.posing_tab)
        self.restJoints_sel.setMaximumSize(QtCore.QSize(24, 24))
        self.restJoints_sel.setText("")
        self.restJoints_sel.setObjectName("restJoints_sel")
        self.horizontalLayout_8.addWidget(self.restJoints_sel)
        self.restJoints_help = QtWidgets.QPushButton(self.posing_tab)
        self.restJoints_help.setMaximumSize(QtCore.QSize(24, 24))
        self.restJoints_help.setText("")
        self.restJoints_help.setObjectName("restJoints_help")
        self.horizontalLayout_8.addWidget(self.restJoints_help)
        self.gridLayout.addLayout(self.horizontalLayout_8, 10, 0, 1, 1)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.unkeyAll = QtWidgets.QPushButton(self.posing_tab)
        self.unkeyAll.setMinimumSize(QtCore.QSize(150, 0))
        self.unkeyAll.setObjectName("unkeyAll")
        self.horizontalLayout_21.addWidget(self.unkeyAll)
        self.unkeyAll_translate = QtWidgets.QCheckBox(self.posing_tab)
        self.unkeyAll_translate.setChecked(True)
        self.unkeyAll_translate.setObjectName("unkeyAll_translate")
        self.horizontalLayout_21.addWidget(self.unkeyAll_translate)
        self.unkeyAll_rotate = QtWidgets.QCheckBox(self.posing_tab)
        self.unkeyAll_rotate.setObjectName("unkeyAll_rotate")
        self.horizontalLayout_21.addWidget(self.unkeyAll_rotate)
        self.unkeyAll_help = QtWidgets.QPushButton(self.posing_tab)
        self.unkeyAll_help.setMaximumSize(QtCore.QSize(24, 24))
        self.unkeyAll_help.setText("")
        self.unkeyAll_help.setObjectName("unkeyAll_help")
        self.horizontalLayout_21.addWidget(self.unkeyAll_help)
        self.gridLayout.addLayout(self.horizontalLayout_21, 9, 0, 1, 1)
        self.tabWidget.addTab(self.posing_tab, "")
        self.iking_tab = QtWidgets.QWidget()
        self.iking_tab.setObjectName("iking_tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.iking_tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.dupSpecial = QtWidgets.QPushButton(self.iking_tab)
        self.dupSpecial.setMinimumSize(QtCore.QSize(178, 0))
        self.dupSpecial.setObjectName("dupSpecial")
        self.horizontalLayout_14.addWidget(self.dupSpecial)
        self.dupSpecial_sources = QtWidgets.QLineEdit(self.iking_tab)
        self.dupSpecial_sources.setObjectName("dupSpecial_sources")
        self.horizontalLayout_14.addWidget(self.dupSpecial_sources)
        self.dupSpecial_sel = QtWidgets.QPushButton(self.iking_tab)
        self.dupSpecial_sel.setMaximumSize(QtCore.QSize(24, 24))
        self.dupSpecial_sel.setText("")
        self.dupSpecial_sel.setObjectName("dupSpecial_sel")
        self.horizontalLayout_14.addWidget(self.dupSpecial_sel)
        self.dupSpecial_help = QtWidgets.QPushButton(self.iking_tab)
        self.dupSpecial_help.setMaximumSize(QtCore.QSize(24, 24))
        self.dupSpecial_help.setText("")
        self.dupSpecial_help.setObjectName("dupSpecial_help")
        self.horizontalLayout_14.addWidget(self.dupSpecial_help)
        self.verticalLayout_4.addLayout(self.horizontalLayout_14)
        self.line_3 = QtWidgets.QFrame(self.iking_tab)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_4.addWidget(self.line_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.ikRPS = QtWidgets.QPushButton(self.iking_tab)
        self.ikRPS.setMinimumSize(QtCore.QSize(178, 0))
        self.ikRPS.setObjectName("ikRPS")
        self.horizontalLayout_10.addWidget(self.ikRPS)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem1)
        self.ikRPS_help = QtWidgets.QPushButton(self.iking_tab)
        self.ikRPS_help.setMaximumSize(QtCore.QSize(24, 24))
        self.ikRPS_help.setText("")
        self.ikRPS_help.setObjectName("ikRPS_help")
        self.horizontalLayout_10.addWidget(self.ikRPS_help)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.ikRPS_sources = QtWidgets.QLineEdit(self.iking_tab)
        self.ikRPS_sources.setObjectName("ikRPS_sources")
        self.horizontalLayout_11.addWidget(self.ikRPS_sources)
        self.ikRPS_sel = QtWidgets.QPushButton(self.iking_tab)
        self.ikRPS_sel.setMaximumSize(QtCore.QSize(24, 24))
        self.ikRPS_sel.setText("")
        self.ikRPS_sel.setObjectName("ikRPS_sel")
        self.horizontalLayout_11.addWidget(self.ikRPS_sel)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.line = QtWidgets.QFrame(self.iking_tab)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_4.addWidget(self.line)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.ikS = QtWidgets.QPushButton(self.iking_tab)
        self.ikS.setMinimumSize(QtCore.QSize(178, 0))
        self.ikS.setObjectName("ikS")
        self.horizontalLayout_12.addWidget(self.ikS)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem2)
        self.ikS_help = QtWidgets.QPushButton(self.iking_tab)
        self.ikS_help.setMaximumSize(QtCore.QSize(24, 24))
        self.ikS_help.setText("")
        self.ikS_help.setObjectName("ikS_help")
        self.horizontalLayout_12.addWidget(self.ikS_help)
        self.verticalLayout_4.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.ikS_sources = QtWidgets.QLineEdit(self.iking_tab)
        self.ikS_sources.setObjectName("ikS_sources")
        self.horizontalLayout_13.addWidget(self.ikS_sources)
        self.ikS_sel = QtWidgets.QPushButton(self.iking_tab)
        self.ikS_sel.setMaximumSize(QtCore.QSize(24, 24))
        self.ikS_sel.setText("")
        self.ikS_sel.setObjectName("ikS_sel")
        self.horizontalLayout_13.addWidget(self.ikS_sel)
        self.verticalLayout_4.addLayout(self.horizontalLayout_13)
        self.line_2 = QtWidgets.QFrame(self.iking_tab)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_4.addWidget(self.line_2)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.ikConstraint = QtWidgets.QPushButton(self.iking_tab)
        self.ikConstraint.setMinimumSize(QtCore.QSize(178, 0))
        self.ikConstraint.setObjectName("ikConstraint")
        self.horizontalLayout_22.addWidget(self.ikConstraint)
        self.ikConstraint_type = QtWidgets.QComboBox(self.iking_tab)
        self.ikConstraint_type.setObjectName("ikConstraint_type")
        self.ikConstraint_type.addItem("")
        self.ikConstraint_type.addItem("")
        self.ikConstraint_type.addItem("")
        self.horizontalLayout_22.addWidget(self.ikConstraint_type)
        self.ikConstraint_help = QtWidgets.QPushButton(self.iking_tab)
        self.ikConstraint_help.setMaximumSize(QtCore.QSize(24, 24))
        self.ikConstraint_help.setText("")
        self.ikConstraint_help.setObjectName("ikConstraint_help")
        self.horizontalLayout_22.addWidget(self.ikConstraint_help)
        self.verticalLayout_4.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.ikConstraint_sources = QtWidgets.QLineEdit(self.iking_tab)
        self.ikConstraint_sources.setText("")
        self.ikConstraint_sources.setObjectName("ikConstraint_sources")
        self.horizontalLayout_23.addWidget(self.ikConstraint_sources)
        self.ikConstraint_sel = QtWidgets.QPushButton(self.iking_tab)
        self.ikConstraint_sel.setMaximumSize(QtCore.QSize(24, 24))
        self.ikConstraint_sel.setText("")
        self.ikConstraint_sel.setObjectName("ikConstraint_sel")
        self.horizontalLayout_23.addWidget(self.ikConstraint_sel)
        self.verticalLayout_4.addLayout(self.horizontalLayout_23)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.tabWidget.addTab(self.iking_tab, "")
        self.misc_tab = QtWidgets.QWidget()
        self.misc_tab.setObjectName("misc_tab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.misc_tab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label = QtWidgets.QLabel(self.misc_tab)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setItalic(True)
        font.setUnderline(True)
        font.setStrikeOut(False)
        font.setBold(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_18.addWidget(self.label)
        self.verticalLayout_5.addLayout(self.horizontalLayout_18)
        self.tab1Layout_2 = QtWidgets.QVBoxLayout()
        self.tab1Layout_2.setObjectName("tab1Layout_2")
        self.importLayout_2 = QtWidgets.QHBoxLayout()
        self.importLayout_2.setObjectName("importLayout_2")
        self.importBtn = QtWidgets.QPushButton(self.misc_tab)
        self.importBtn.setMinimumSize(QtCore.QSize(150, 0))
        self.importBtn.setObjectName("importBtn")
        self.importLayout_2.addWidget(self.importBtn)
        self.delayAnim = QtWidgets.QCheckBox(self.misc_tab)
        self.delayAnim.setObjectName("delayAnim")
        self.importLayout_2.addWidget(self.delayAnim)
        self.delayBy = QtWidgets.QSpinBox(self.misc_tab)
        self.delayBy.setEnabled(True)
        self.delayBy.setObjectName("delayBy")
        self.importLayout_2.addWidget(self.delayBy)
        self.importBtn_help = QtWidgets.QPushButton(self.misc_tab)
        self.importBtn_help.setMaximumSize(QtCore.QSize(24, 24))
        self.importBtn_help.setText("")
        self.importBtn_help.setObjectName("importBtn_help")
        self.importLayout_2.addWidget(self.importBtn_help)
        self.tab1Layout_2.addLayout(self.importLayout_2)
        self.verticalLayout_5.addLayout(self.tab1Layout_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.poseAutomate = QtWidgets.QPushButton(self.misc_tab)
        self.poseAutomate.setMinimumSize(QtCore.QSize(150, 0))
        self.poseAutomate.setObjectName("poseAutomate")
        self.horizontalLayout_19.addWidget(self.poseAutomate)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.ikAutomate = QtWidgets.QPushButton(self.misc_tab)
        self.ikAutomate.setMinimumSize(QtCore.QSize(150, 0))
        self.ikAutomate.setObjectName("ikAutomate")
        self.horizontalLayout_20.addWidget(self.ikAutomate)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_20)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        self.line_6 = QtWidgets.QFrame(self.misc_tab)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_5.addWidget(self.line_6)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.exportCam = QtWidgets.QPushButton(self.misc_tab)
        self.exportCam.setMinimumSize(QtCore.QSize(150, 0))
        self.exportCam.setObjectName("exportCam")
        self.horizontalLayout_24.addWidget(self.exportCam)
        self.exportCam_save = QtWidgets.QCheckBox(self.misc_tab)
        self.exportCam_save.setChecked(True)
        self.exportCam_save.setObjectName("exportCam_save")
        self.horizontalLayout_24.addWidget(self.exportCam_save)
        self.exportCam_locs = QtWidgets.QCheckBox(self.misc_tab)
        self.exportCam_locs.setChecked(True)
        self.exportCam_locs.setObjectName("exportCam_locs")
        self.horizontalLayout_24.addWidget(self.exportCam_locs)
        self.exportCam_label = QtWidgets.QLabel(self.misc_tab)
        self.exportCam_label.setObjectName("exportCam_label")
        self.horizontalLayout_24.addWidget(self.exportCam_label)
        self.exportCam_mult = QtWidgets.QSpinBox(self.misc_tab)
        self.exportCam_mult.setObjectName("exportCam_mult")
        self.horizontalLayout_24.addWidget(self.exportCam_mult)
        self.exportCam_help = QtWidgets.QPushButton(self.misc_tab)
        self.exportCam_help.setMaximumSize(QtCore.QSize(24, 24))
        self.exportCam_help.setText("")
        self.exportCam_help.setObjectName("exportCam_help")
        self.horizontalLayout_24.addWidget(self.exportCam_help)
        self.verticalLayout_5.addLayout(self.horizontalLayout_24)
        self.line_7 = QtWidgets.QFrame(self.misc_tab)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_5.addWidget(self.line_7)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.locTrans = QtWidgets.QPushButton(self.misc_tab)
        self.locTrans.setMinimumSize(QtCore.QSize(180, 0))
        self.locTrans.setObjectName("locTrans")
        self.horizontalLayout_15.addWidget(self.locTrans)
        self.line_4 = QtWidgets.QFrame(self.misc_tab)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_15.addWidget(self.line_4)
        self.locTrans2 = QtWidgets.QPushButton(self.misc_tab)
        self.locTrans2.setMinimumSize(QtCore.QSize(180, 0))
        self.locTrans2.setObjectName("locTrans2")
        self.horizontalLayout_15.addWidget(self.locTrans2)
        self.line_5 = QtWidgets.QFrame(self.misc_tab)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_15.addWidget(self.line_5)
        self.locTrans_help = QtWidgets.QPushButton(self.misc_tab)
        self.locTrans_help.setMaximumSize(QtCore.QSize(24, 24))
        self.locTrans_help.setText("")
        self.locTrans_help.setObjectName("locTrans_help")
        self.horizontalLayout_15.addWidget(self.locTrans_help)
        self.verticalLayout_5.addLayout(self.horizontalLayout_15)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem6)
        self.tabWidget.addTab(self.misc_tab, "")
        self.keyframes_tab = QtWidgets.QWidget()
        self.keyframes_tab.setObjectName("keyframes_tab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.keyframes_tab)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.unchangingKeys = QtWidgets.QPushButton(self.keyframes_tab)
        self.unchangingKeys.setMinimumSize(QtCore.QSize(175, 0))
        self.unchangingKeys.setObjectName("unchangingKeys")
        self.horizontalLayout_16.addWidget(self.unchangingKeys)
        self.unchangingKeyranges = QtWidgets.QPushButton(self.keyframes_tab)
        self.unchangingKeyranges.setMinimumSize(QtCore.QSize(175, 0))
        self.unchangingKeyranges.setObjectName("unchangingKeyranges")
        self.horizontalLayout_16.addWidget(self.unchangingKeyranges)
        self.unchangingKeys_rec = QtWidgets.QCheckBox(self.keyframes_tab)
        self.unchangingKeys_rec.setMinimumSize(QtCore.QSize(75, 0))
        self.unchangingKeys_rec.setObjectName("unchangingKeys_rec")
        self.horizontalLayout_16.addWidget(self.unchangingKeys_rec)
        self.unchangingKeys_help = QtWidgets.QPushButton(self.keyframes_tab)
        self.unchangingKeys_help.setMaximumSize(QtCore.QSize(24, 24))
        self.unchangingKeys_help.setText("")
        self.unchangingKeys_help.setObjectName("unchangingKeys_help")
        self.horizontalLayout_16.addWidget(self.unchangingKeys_help)
        self.verticalLayout_6.addLayout(self.horizontalLayout_16)
        self.unchangingKeys_view = QtWidgets.QTableView(self.keyframes_tab)
        self.unchangingKeys_view.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.unchangingKeys_view.setGridStyle(QtCore.Qt.NoPen)
        self.unchangingKeys_view.setObjectName("unchangingKeys_view")
        self.verticalLayout_6.addWidget(self.unchangingKeys_view)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.removeAll_unchKeys = QtWidgets.QPushButton(self.keyframes_tab)
        self.removeAll_unchKeys.setMinimumSize(QtCore.QSize(150, 0))
        self.removeAll_unchKeys.setObjectName("removeAll_unchKeys")
        self.horizontalLayout_17.addWidget(self.removeAll_unchKeys)
        self.removeSel_unchKeys = QtWidgets.QPushButton(self.keyframes_tab)
        self.removeSel_unchKeys.setMinimumSize(QtCore.QSize(150, 0))
        self.removeSel_unchKeys.setObjectName("removeSel_unchKeys")
        self.horizontalLayout_17.addWidget(self.removeSel_unchKeys)
        self.verticalLayout_6.addLayout(self.horizontalLayout_17)
        self.tabWidget.addTab(self.keyframes_tab, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        RigHelper.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(RigHelper)
        self.statusbar.setObjectName("statusbar")
        RigHelper.setStatusBar(self.statusbar)

        self.retranslateUi(RigHelper)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(RigHelper)

    def retranslateUi(self, RigHelper):
        RigHelper.setWindowTitle(QtWidgets.QApplication.translate("RigHelper", "MainWindow", None, -1))
        self.keyAll.setText(QtWidgets.QApplication.translate("RigHelper", "Key All", None, -1))
        self.keyAll_translate.setText(QtWidgets.QApplication.translate("RigHelper", "Translate", None, -1))
        self.keyAll_rotate.setText(QtWidgets.QApplication.translate("RigHelper", "Rotate", None, -1))
        self.keyAll_help.setToolTip(QtWidgets.QApplication.translate("RigHelper", "See script editor for message.", None, -1))
        self.selectGrp.setText(QtWidgets.QApplication.translate("RigHelper", "Select Group", None, -1))
        self.selectGrp_out.setPlaceholderText(QtWidgets.QApplication.translate("RigHelper", "Path to Group Transform", None, -1))
        self.selectGrp_help.setToolTip(QtWidgets.QApplication.translate("RigHelper", "See script editor for message.", None, -1))
        self.centerGrp.setText(QtWidgets.QApplication.translate("RigHelper", "Center Group", None, -1))
        self.centerGrp_help.setToolTip(QtWidgets.QApplication.translate("RigHelper", "See script editor for message.", None, -1))
        self.zeroZ.setText(QtWidgets.QApplication.translate("RigHelper", "Zero-Out All", None, -1))
        self.zeroZ_sources.setPlaceholderText(QtWidgets.QApplication.translate("RigHelper", "Skipable joints", None, -1))
        self.zeroZ_sel.setToolTip(QtWidgets.QApplication.translate("RigHelper", "Use selected joints.", None, -1))
        self.zeroZ_help.setToolTip(QtWidgets.QApplication.translate("RigHelper", "See script editor for message.", None, -1))
        self.zeroLegs.setText(QtWidgets.QApplication.translate("RigHelper", "Zero Legchain", None, -1))
        self.zeroLegs_sources.setPlaceholderText(QtWidgets.QApplication.translate("RigHelper", "Targets", None, -1))
        self.zeroLegs_sel.setToolTip(QtWidgets.QApplication.translate("RigHelper", "Use selected joints.", None, -1))
        self.zeroLegs_help.setToolTip(QtWidgets.QApplication.translate("RigHelper", "See script editor for message.", None, -1))
        self.zeroSpines.setText(QtWidgets.QApplication.translate("RigHelper", "Zero Spines", None, -1))
        self.zeroSpines_sources.setPlaceholderText(QtWidgets.QApplication.translate("RigHelper", "Targets", None, -1))
        self.zeroSpines_sel.setToolTip(QtWidgets.QApplication.translate("RigHelper", "Use selected joints.", None, -1))
        self.zeroSpines_help.setToolTip(QtWidgets.QApplication.translate("RigHelper", "See script editor for message.", None, -1))
        self.poseArms.setText(QtWidgets.QApplication.translate("RigHelper", "Pose Armchain", None, -1))
        self.poseArms_sources.setPlaceholderText(QtWidgets.QApplication.translate("RigHelper", "Targets", None, -1))
        self.poseArms_sel.setToolTip(QtWidgets.QApplication.translate("RigHelper", "Use selected joints.", None, -1))
        self.poseArms_help.setToolTip(QtWidgets.QApplication.translate("RigHelper", "See script editor for message.", None, -1))
        self.mirrorJoints.setText(QtWidgets.QApplication.translate("RigHelper", "Mirror Jointchain", None, -1))
        self.mirrorJoints_sources.setPlaceholderText(QtWidgets.QApplication.translate("RigHelper", "Source, Target", None, -1))
        self.mirrorJoints_sel.setToolTip(QtWidgets.QApplication.translate("RigHelper", "Use selected joints.", None, -1))
        self.mirrorJoints_help.setToolTip(QtWidgets.QApplication.translate("RigHelper", "See script editor for message.", None, -1))
        self.restJoints.setText(QtWidgets.QApplication.translate("RigHelper", "Rest Joints", None, -1))
        self.restJoints_sources.setPlaceholderText(QtWidgets.QApplication.translate("RigHelper", "Source, Target", None, -1))
        self.restJoints_sel.setToolTip(QtWidgets.QApplication.translate("RigHelper", "Use selected joints.", None, -1))
        self.restJoints_help.setToolTip(QtWidgets.QApplication.translate("RigHelper", "See script editor for message.", None, -1))
        self.unkeyAll.setText(QtWidgets.QApplication.translate("RigHelper", "Unkey All", None, -1))
        self.unkeyAll_translate.setText(QtWidgets.QApplication.translate("RigHelper", "Translate", None, -1))
        self.unkeyAll_rotate.setText(QtWidgets.QApplication.translate("RigHelper", "Rotate", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.posing_tab), QtWidgets.QApplication.translate("RigHelper", "T-Posing", None, -1))
        self.dupSpecial.setText(QtWidgets.QApplication.translate("RigHelper", "Duplicate Special", None, -1))
        self.dupSpecial_sources.setPlaceholderText(QtWidgets.QApplication.translate("RigHelper", "Source copy name, Target copy name", None, -1))
        self.ikRPS.setText(QtWidgets.QApplication.translate("RigHelper", "Ik-Transfer (RPSolver)", None, -1))
        self.ikRPS_sources.setPlaceholderText(QtWidgets.QApplication.translate("RigHelper", "Start Jnt, End Jnt, Source Handle Jnt, Polevec Jnt", None, -1))
        self.ikS.setText(QtWidgets.QApplication.translate("RigHelper", "Ik-Transfer (Spline)", None, -1))
        self.ikS_sources.setPlaceholderText(QtWidgets.QApplication.translate("RigHelper", "Start Jnt, End Jnt, Up Handle Source, Low Handle Source", None, -1))
        self.ikConstraint.setText(QtWidgets.QApplication.translate("RigHelper", "Contraint Source-Target", None, -1))
        self.ikConstraint_type.setItemText(0, QtWidgets.QApplication.translate("RigHelper", "parentConstraint", None, -1))
        self.ikConstraint_type.setItemText(1, QtWidgets.QApplication.translate("RigHelper", "pointConstraint", None, -1))
        self.ikConstraint_type.setItemText(2, QtWidgets.QApplication.translate("RigHelper", "orientConstraint", None, -1))
        self.ikConstraint_sources.setPlaceholderText(QtWidgets.QApplication.translate("RigHelper", "Source, Target", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.iking_tab), QtWidgets.QApplication.translate("RigHelper", "Ik-Tools", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("RigHelper", "Videopose3D", None, -1))
        self.importBtn.setText(QtWidgets.QApplication.translate("RigHelper", "Import Skeleton", None, -1))
        self.delayAnim.setText(QtWidgets.QApplication.translate("RigHelper", "Delay Animation", None, -1))
        self.poseAutomate.setText(QtWidgets.QApplication.translate("RigHelper", "T-Pose Character", None, -1))
        self.ikAutomate.setText(QtWidgets.QApplication.translate("RigHelper", "Ik Character", None, -1))
        self.exportCam.setText(QtWidgets.QApplication.translate("RigHelper", "Export Cam", None, -1))
        self.exportCam_save.setText(QtWidgets.QApplication.translate("RigHelper", "Save", None, -1))
        self.exportCam_locs.setText(QtWidgets.QApplication.translate("RigHelper", "Locs", None, -1))
        self.exportCam_label.setText(QtWidgets.QApplication.translate("RigHelper", "Multiply", None, -1))
        self.locTrans.setText(QtWidgets.QApplication.translate("RigHelper", "Create Loc-Transformer", None, -1))
        self.locTrans2.setText(QtWidgets.QApplication.translate("RigHelper", "Remove Loc-Transformer", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.misc_tab), QtWidgets.QApplication.translate("RigHelper", "Misc", None, -1))
        self.unchangingKeys.setText(QtWidgets.QApplication.translate("RigHelper", "Unchanging Keyframes", None, -1))
        self.unchangingKeyranges.setText(QtWidgets.QApplication.translate("RigHelper", "Unchanging Key-Ranges", None, -1))
        self.unchangingKeys_rec.setText(QtWidgets.QApplication.translate("RigHelper", "Recurse", None, -1))
        self.removeAll_unchKeys.setText(QtWidgets.QApplication.translate("RigHelper", "Remove All", None, -1))
        self.removeSel_unchKeys.setText(QtWidgets.QApplication.translate("RigHelper", "Remove Selected", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.keyframes_tab), QtWidgets.QApplication.translate("RigHelper", "Keyframes", None, -1))

